### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "With over 40 years experience in office and project management, accounting and staff recruitment, training and analysis, here is a man who can get the job done."

### CONTACT SETTINGS ###

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: Charles.TrainingBallarat@gmail.com
contact_comment: Get in touch today to grab a quote, or if you just want to know something more!

#Enable of Disable Site Sections
services_enabled: true
testimonial_enabled: false
