### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "With over 40 years experience in office and project management, accounting and staff recruitment, training and analysis, here is a man who can get the job done."

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: http://www.linkedin.com/profile/view?id=98110841

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: Charles.TrainingBallarat@gmail.com
contact_comment: Get in touch today to grab a quote, or if you just want to know something more!

#Enable of Disable Site Sections
blog_enabled: false
faq_enabled: false
portfolio_enabled: false
services_enabled: true
testimonial_enabled: false
clients_enabled: false
members_enabled: false
